name: Build Windows Image

on:
  push:
    branches:
      - master
    paths:
    - 'build/images/**'
  workflow_dispatch:
    inputs:
      build_baseline_image:
        description: "Build new baseline image?"
        required: false
        default: true
        type: boolean
      build_generalized_image:
        description: "Build a new generalized image?"
        required: false
        default: true
        type: boolean

jobs:
  setup_infra:
    name: Build Supporting Infrastructure
    uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/deploy-gallery-2.yml@master
    with:
      compute_gallery_rg: vaidhee-rg
      compute_gallery: vaidhee_rg_gallery
      image_definition_baseline: vaidhee-rg-baseline-windows2022
      image_definition_generalized: vaidhee-rg-generalized-windows2022
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
      vnet_cidr: ${{ vars.VNET_CIDR }}
      ad_group: ${{ vars.AD_GROUP }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}

  # setup_infra_baseline:
  #   name: Build Supporting Infrastructure for baseline image
  #   uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/deploy-gallery.yml@master
  #   with:
  #     compute_gallery_rg: vaidhee-rg
  #     compute_gallery: vaidhee_rg_baseline_gallery
  #     image_definition: vaidhee-rg-baseline-windows2022
  #     client_id: ${{ vars.CLIENT_ID }}
  #     subscription_id: ${{ vars.SUBSCRIPTION_ID }}
  #     tenant_id: ${{ vars.TENANT_ID }}
  #   secrets:
  #     client_secret: ${{ secrets.CLIENT_SECRET }}

  # setup_infra_generalized:
  #   name: Build Supporting Infrastructure for generalized image
  #   uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/deploy-gallery.yml@master
  #   with:
  #     compute_gallery_rg: vaidhee-rg
  #     compute_gallery: vaidhee_rg_generalized_gallery
  #     image_definition: vaidhee-rg-generalized-windows2022
  #     client_id: ${{ vars.CLIENT_ID }}
  #     subscription_id: ${{ vars.SUBSCRIPTION_ID }}
  #     tenant_id: ${{ vars.TENANT_ID }}
  #   secrets:
  #     client_secret: ${{ secrets.CLIENT_SECRET }}

  build_image:
    name: Call Packer Build for image build
    if: ${{ github.event.inputs.build_baseline_image != 'false' }}
    permissions:
      contents: write
    needs: setup_infra
    uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/packer-build.yml@master
    with:
      packer_folder: build/images/baseline
      compute_gallery_rg: vaidhee-rg
      compute_gallery: vaidhee_rg_gallery
      image_definition: vaidhee-rg-generalized-windows2022
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}

  # build_baseline_image:
  #   name: Call Packer Build for baseline image
  #   if: ${{ github.event.inputs.build_baseline_image != 'false' }}
  #   permissions:
  #     contents: write
  #   needs: setup_infra
  #   uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/packer-build.yml@master
  #   with:
  #     packer_folder: build/images/baseline
  #     compute_gallery_rg: vaidhee-rg
  #     compute_gallery: vaidhee_rg_gallery
  #     image_definition_baseline: vaidhee-rg-baseline-windows2022
  #     image_definition_generalized: vaidhee-rg-generalized-windows2022
  #     client_id: ${{ vars.CLIENT_ID }}
  #     subscription_id: ${{ vars.SUBSCRIPTION_ID }}
  #     tenant_id: ${{ vars.TENANT_ID }}
  #   secrets:
  #     client_secret: ${{ secrets.CLIENT_SECRET }}

  build_generalized_image:
    name: Call Packer Build for genralized image
    if: |
      github.event.inputs.build_generalized_image != 'false' &&
      (needs.build_baseline_image.result == 'success' || needs.build_baseline_image.result == 'skipped')
    permissions:
      contents: write
    needs: [setup_infra, build_baseline_image]
    uses: VaidheeswaranS/packer-builds-shared-workflows/.github/workflows/packer-build.yml@master
    with:
      packer_folder: build/images/generalized
      compute_gallery_rg: vaidhee-rg
      compute_gallery: vaidhee_rg_gallery
      image_definition: vaidhee-rg-generalized-windows2022
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}